app:
  name: airqo-stage-meta-data-api
  label: meta-data-api
  namespace: staging
  configmap: stage-meta-data-api-config

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/airqo-stage-meta-data-api
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 300m
    memory: 400Mi
  requests:
    # Average usage was 0.1 vCPU and 200Mi over the last 7 days
    cpu: 100m
    memory: 200Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: stage-meta-data-api-config-files

nodeSelector: {}
tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
