---
- name: Initialize the cluster
  # Skip kube-proxy installation since we use cilium instead
  shell: kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory
  become: true
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
