---
- name: Install kubectl
  apt:
    name: kubectl=1.26.*
    state: present
    force: true # allow downgrades

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy the kube config fileremote_src
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config

- name: Install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
