apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-kcca-measurements-consumer
  namespace: staging
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: stage-kcca-measurements-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stage-kcca-measurements-consumer
    spec:
      containers:
      - name: stage-kcca-measurements-consumer
        image: us.gcr.io/airqo-250220/stage-measurements-consumer:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        envFrom:
          - configMapRef:
              name: stage-kcca-measurements-consumer-config
