app:
  name: stage-fault-detection-api
  label: fault-detection
  namespace: staging
  configmap: stage-fault-detection-api-config

initContainers:
  container1:
    image:
      repository: gcr.io/airqo-250220/stage-train-catboost-model
      pullPolicy: Always
      tag: latest
  container2:
    image:
      repository: gcr.io/airqo-250220/stage-train-lstm-model
      pullPolicy: Always
      tag: latest

replicaCount: 2

revisionHistoryLimit: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - compute

image:
  repository: gcr.io/airqo-250220/stage-fault-detection-api
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    # Average usage was 0.0005 vCPU and 200Mi over the last 30 days
    cpu: 100m
    memory: 200Mi

volumeMounts:
  - name: shared-data
    mountPath: /usr/models

volumes:
  - name: shared-data
    emptyDir: {}

nodeSelector: {}
tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 30013

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
