app:
  name: airqo-device-registry-api
  label: device-reg-api
  namespace: production
  configmap: env-device-registry-production

replicaCount: 3

revisionHistoryLimit: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose

image:
  repository: gcr.io/airqo-250220/airqo-device-registry-api
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 900Mi
  requests:
    # Average usage was 0.0005 vCPU and 1Gi over the last 30 days
    cpu: 5m
    memory: 600Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: device-registry-config-files

nodeSelector: {}

tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 3000
  protocol: TCP
  targetPort: 3000
  nodePort: 30002

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
