apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-processed-device-measurements-topic 
  namespace: production
  labels:
    strimzi.io/cluster: "prod-kafka-cluster"
spec:
  topicName: airqo-streams-processed-device-measurements-topic 
  partitions: 3
  replicas: 2
  config:
    retention.ms: 3600000
