apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-transformed-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 21600000 # 6 hours
    segment.bytes: 1073741824
