apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-raw-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 1800000
    segment.bytes: 1073741824
