apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-kafka-cluster
  namespace: staging
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap.192.168.49.2.nip.io
          brokers:
          - broker: 0
            host: broker-0.192.168.49.2.nip.io
          # - broker: 1
          #   host: broker-1.192.168.49.2.nip.io
          # - broker: 2
          #   host: broker-2.192.168.49.2.nip.io
      # - name: external
      #   port: 9094
      #   type: nodeport
      #   tls: false
      #   configuration:
      #     bootstrap:
      #       nodePort: 31000
      #     brokers:
      #       - broker: 0
      #         nodePort: 31001
      #         # advertisedHost: XX.XXX.XXX.XX
      #       - broker: 1
      #         nodePort: 31002
      #         # advertisedHost: XX.XXX.XXX.XX
      #       - broker: 2
      #         nodePort: 31003
      #         # advertisedHost: XX.XXX.XXX.XX
      #       - broker: 3
      #         nodePort: 31004
      #         # advertisedHost: XX.XXX.XXX.XX
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  entityOperator:
    topicOperator: {}
    userOperator: {}

