apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: kcca-source-connector-hourly
  namespace: staging
  labels:
    strimzi.io/cluster: kcca-source-connector-cluster
spec:
  class: net.airqo.connectors.KccaSourceConnector
  tasksMax: 2
  config:
    topic: kcca-streams-raw-device-measurements-topic
    clarityApiKey: ${file:/opt/kafka/external-configuration/connector-config/clarity-credentials.properties:clarity_api_key}
    clarityApiBaseUrl: https://clarity-data-api.clarity.io/v1/
    pollInterval: 3600000  # set to 1 hour (3600 * 1000). Note that the connector fetches for last 2 hours
    average: hour
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
