app:
  name: prod-gpmodel
  namespace: production
  configmap: env-gp-model-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-gp-model-job
  tag: prod-6d727c2d-1680259714
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
