app:
  name: stage-gpmodel
  namespace: staging
  configmap: env-gp-model-staging
image:
  repository: gcr.io/airqo-250220/airqo-stage-gp-model-job
  tag: stage-5469f6d6-1670411700
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
