app:
  name: stage-gpmodel
  namespace: staging
  configmap: env-gp-model-staging
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-gp-model-job
  tag: stage-a93d73e8-1677156910
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
