app:
  name: prod-gpmodel
  namespace: production
  configmap: env-gp-model-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-gp-model-job
  tag: prod-1b6e5014-1683239318
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
