apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-body-size:  "200m"
  client-max-body-size: "200m"
  location-snippets: "  
    auth_request /auth;
    error_page 500 = @internal_server_error;
    error_page 404 = @page_not_found;
    error_page 403 = @access_denied;
    error_page 401 = @unauthorized;"
  server-snippets: "
    location @internal_server_error { return 500 '{\"error\": \"Something went wrong!\"}'; }
    location @page_not_found { return 404 '{\"error\": \"Page not found :(\"}'; }
    location @access_denied { return 403 '{\"error\": \"Access denied :|\"}'; }
    location @unauthorized { return 401 '{\"error\": \"Unauthorized\"}'; }

    location = /auth {
      if ($request_method = 'OPTIONS') { return 204; }      
      
      if ($request_uri = '/') { return 200; }
      if ($request_uri = '/login') { return 200; }
      if ($request_uri ~ '(/api/v1/users/loginUser)|(/api/v2/users/loginUser)') { return 200; }
      if ($request_uri ~ '(/api/v1/users/forgotPassword)|(/api/v2/users/forgotPassword)') { return 200; }
      if ($request_uri ~ '(/api/v1/users/candidates/register)|(/api/v2/users/candidates/register)') { return 200; }
      if ($request_uri ~ '/static/') { return 200; }

      internal;
      proxy_method            POST;
      proxy_pass              http://airqo-stage-auth-api-svc.staging.svc.cluster.local:3000/api/v1/users/verify?tenant=airqo;
      proxy_pass_request_body off;
      proxy_set_header        Content-Length '';
      proxy_set_header        X-Original-URI $request_uri;
    }
    "