apiVersion: v1
kind: ConfigMap
data:
  proxy-body-size:  "200m"
  client-max-body-size: "200m"
  location-snippets: "  
    auth_request /auth;
    error_page 500 = @internal_server_error;
    error_page 404 = @page_not_found;
    error_page 403 = @access_denied;
    error_page 401 = @unauthorized;"
  server-snippets: "
    location @internal_server_error { return 500 'Something went wrong'; }
    location @page_not_found { return 404 'Page not found'; }
    location @access_denied { return 403 'Access denied'; }
    location @unauthorized { return 401 'Unauthorized'; }

    location = /auth {
      if ($request_uri = '/') { return 200; }
      if ($request_uri = '/login') { return 200; }
      if ($request_uri ~ '(/api/v1/users/loginUser)|(/api/v2/users/loginUser)') { return 200; }
      if ($request_uri ~ '(/api/v1/users/forgotPassword)|(/api/v2/users/forgotPassword)') { return 200; }
      if ($request_uri ~ '(/api/v1/users/candidates/register)|(/api/v2/users/candidates/register)') { return 200; }

      internal;
      proxy_method            POST;
      proxy_pass              http://airqo-stage-auth-api-svc.staging.svc.cluster.local:3000/api/v1/users/verify?tenant=airqo;
      proxy_pass_request_body off;
      proxy_set_header        Content-Length '';
      proxy_set_header        X-Original-URI $request_uri;
    }"
metadata:
  name: nginx-config
  namespace: nginx-ingress

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stage-ingress-platform-resource
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:    
    - host: staging-airqalibrate.airqo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-calibrate-app-svc
                port: 
                  number: 80
    - host: staging-platform.airqo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-platform-ui-svc
                port: 
                  number: 80
          - path: /airflow
            pathType: Prefix
            backend:
              service:
                name: airflow-svc
                port: 
                  number: 8080
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-auth-api-svc
                port: 
                  number: 3000
          - path: /api/v2/users
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-auth-api-svc
                port: 
                  number: 3000
          - path: /api/v1/devices
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-device-registry-api-svc
                port: 
                  number: 3000
          - path: /api/v2/devices
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-device-registry-api-svc
                port: 
                  number: 3000
          - path: /api/v1/data
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-data-mgt-api-svc
                port: 
                  number: 3000
          - path: /api/v2/data
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-data-mgt-api-svc
                port: 
                  number: 3000
          - path: /api/v1/locate/map
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-locate-api-svc
                port: 
                  number: 4001
          - path: /api/v2/locate/map
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-locate-api-svc
                port: 
                  number: 4001
          - path: /api/v1/analytics
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-analytics-api-svc
                port: 
                  number: 5000
          - path: /api/v2/analytics
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-analytics-api-svc
                port: 
                  number: 5000
          - path: /api/v1/predict
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-prediction-api-svc
                port: 
                  number: 5000
          - path: /api/v2/predict
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-prediction-api-svc
                port: 
                  number: 5000
          - path: /api/v1/monitor
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-device-monitor-api-svc
                port: 
                  number: 4001
          - path: /api/v2/monitor
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-device-monitor-api-svc
                port: 
                  number: 4001
          - path: /api/v1/calibrate
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-calibrate-api-svc
                port: 
                  number: 4001
          - path: /api/v2/calibrate
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-calibrate-api-svc
                port: 
                  number: 4001
          - path: /api/v1/predict-faults
            pathType: Prefix
            backend:
              service:
                name: stage-fault-detection-api-svc
                port: 
                  number: 4001
          - path: /api/v1/incentives
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-incentives-api-svc
                port: 
                  number: 3000
          - path: /api/v2/incentives
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-incentives-api-svc
                port: 
                  number: 3000
          - path: /api/v1/meta-data
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-meta-data-api-svc
                port: 
                  number: 4001
          - path: /api/v1/notifications
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-notification-api-svc
                port: 
                  number: 8080
          - path: /api/v1/view
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-view-api-svc
                port: 
                  number: 8080
          - path: /api/v1/views
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-view-api-svc
                port: 
                  number: 8081
          - path: /api/v1/network-uptime
            pathType: Prefix
            backend:
              service:
                name: airqo-stage-network-uptime-api-svc
                port: 
                  number: 8501