apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: airflow
  namespace: pipeline
spec:
  host: staging-platform.airqo.net
  upstreams:
    - name: airflow
      service: airflow-svc
      port: 8080
  subroutes:
    - path: /airflow
      action:
        pass: airflow

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: staging-virtual-server
  namespace: staging
spec:
  host: staging-platform.airqo.net
  upstreams:
    - name: platform-ui
      service: airqo-stage-platform-ui-svc
      port: 80
    - name: auth-service
      service: airqo-stage-auth-api-svc
      port: 3000
    - name: device-registry
      service: airqo-stage-device-registry-api-svc
      port: 3000
    - name: data-mgt
      service: airqo-stage-data-mgt-api-svc
      port: 3000
    - name: locate
      service: airqo-stage-locate-api-svc
      port: 4001
    - name: analytics
      service: airqo-stage-analytics-api-svc
      port: 5000
    - name: predict
      service: airqo-stage-prediction-api-svc
      port: 5000
    - name: monitor
      service: airqo-stage-device-monitor-api-svc
      port: 4001
    - name: calibrate
      service: airqo-stage-calibrate-api-svc
      port: 4001
    - name: incentives
      service: airqo-stage-incentives-api-svc
      port: 3000
    - name: meta-data
      service: airqo-stage-meta-data-api-svc
      port: 4001
    - name: view
      service: airqo-stage-view-api-svc
      port: 8080
    - name: views
      service: airqo-stage-locate-api-svc
      port: 8081
    - name: network-uptime
      service: airqo-stage-network-uptime-api-svc
      port: 8501
    - name: fault-detection
      service: stage-fault-detection-api-svc
      port: 4001
    - name: notifications
      service: airqo-stage-notification-api-svc
      port: 8080
  routes:
    - path: /
      action:
        pass: platform-ui
    - path: /airflow
      route: pipeline/airflow
    - path: /api\/v[1-2]\/users
      action:
        pass: auth-service
    - path: /api\/v[1-2]\/devicesdevices
      action:
        pass: device-registry
    - path: /api\/v[1-2]\/devicesdata
      action:
        pass: data-mgt
    - path: /api\/v[1-2]\/deviceslocate/map
      action:
        pass: locate
    - path: /api\/v[1-2]\/devicesanalytics
      action:
        pass: analytics
    - path: /api\/v[1-2]\/devicespredict
      action:
        pass: predict
    - path: /api\/v[1-2]\/devicesmonitor
      action:
        pass: monitor
    - path: /api\/v[1-2]\/devicescalibrate
      action:
        pass: calibrate
    - path: /api\/v[1-2]\/devicesincentives
      action:
        pass: incentives
    - path: /api\/v[1-2]\/devicesmeta-data
      action:
        pass: meta-data
    - path: /api\/v[1-2]\/devicesview
      action:
        pass: view
    - path: /api\/v[1-2]\/devicesviews
      action:
        pass: views
    - path: /api\/v[1-2]\/devicesnetwork-uptime
      action:
        pass: network-uptime
    - path: /api\/v[1-2]\/devicespredict-faults
      action:
        pass: fault-detection
    - path: /api\/v[1-2]\/devicesnotifications
      action:
        pass: notifications
