apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kcca-source-connector-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: localhost:5000/kcca-kafka-source-connector-test
  replicas: 1
  bootstrapServers: <BOOTSTRAP_SERVERS>
  config:
    group.id: kcca-source-connector-cluster
    offset.storage.topic: kcca-source-connector-cluster-offsets
    config.storage.topic: kcca-source-connector-cluster-configs
    status.storage.topic: kcca-source-connector-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10


