app:
  name: airqo-stage-data-mgt-api
  label: sta-data-mgt
  namespace: staging
  configmap: data-mgt-api-config
replicaCount: 2
image:
  repository: gcr.io/airqo-250220/airqo-stage-data-mgt-api
  tag: stage-5469f6d6-1670411700
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 70Mi
ingress:
  enabled: false
service:
  type: NodePort
  port: 3000
  protocol: TCP
  targetPort: 3000
  nodePort: 31001
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
