app:
  name: airqo-data-mgt-api
  label: data-mgt-api
  namespace: production
  configmap: data-mgt-api-config

replicaCount: 2

revisionHistoryLimit: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory

image:
  repository: gcr.io/airqo-250220/airqo-data-mgt-api
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 50m
    memory: 120Mi
  requests:
    # Average usage was 0.0005 vCPU and 80Mi over the last 30 days
    cpu: 5m
    memory: 70Mi

nodeSelector: {}

tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 3000
  protocol: TCP
  targetPort: 3000
  nodePort: 30001

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
