apiVersion: v1
kind: Namespace
metadata:
  name: development

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: development
spec:
  hard:
    cpu: 2000
    memory: 4Gi
    pods: 10
    replicationcontrollers: 20
    resourcequotas: 1
    persistentvolumeclaims: 1