apiVersion: v1
kind: Namespace
metadata:
  name: message-broker

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: message-broker-quota
  namespace: message-broker
spec:
  hard:
    limits.cpu: 1000
    limits.memory: 2Gi
    resourcequotas: 1