apiVersion: v1
kind: Namespace
metadata:
  name: pipeline


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pipeline-quota
  namespace: pipeline
spec:
  hard:
    limits.cpu: 4000
    limits.memory: 8Gi
    resourcequotas: 1