apiVersion: v1
kind: Namespace
metadata:
  name: production


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    limits.cpu: 5000
    limits.memory: 10Gi
    resourcequotas: 1