apiVersion: v1
kind: Namespace
metadata:
  name: staging


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    limits.cpu: 4000
    limits.memory: 8Gi
    resourcequotas: 1