apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: development

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-role
  namespace: development
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-rolebinding
  namespace: development
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-admin-role

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-view-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-dashboard-view-clusterrole
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services/proxy"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["proxy"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-dashboard-view-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-dashboard-view-clusterrole