apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: development

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-role
  namespace: development
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-rolebinding
  namespace: development
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-admin

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-view-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view