apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: {{ .Values.topics.transformedMeasurements.producer.username }}
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.cluster }}
spec:
  authentication:
    type: {{ .Values.topics.transformedMeasurements.producer.authentication.type }}
  authorization:
    type: {{ .Values.topics.transformedMeasurements.producer.authorization.type }}
    acls:
      - resource:
          type: topic
          name: airqo-streams-calibrated-device-measurements-topic 
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: airqo-streams-calibrated-device-measurements-topic 
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: kcca-streams-transformed-device-measurements-topic 
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: kcca-streams-transformed-device-measurements-topic 
          patternType: literal
        operation: Write
        host: "*"

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: {{ .Values.topics.transformedMeasurements.consumer.username }}
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.cluster }}
spec:
  authentication:
    type: {{ .Values.topics.transformedMeasurements.consumer.authentication.type }}
  authorization:
    type: {{ .Values.topics.transformedMeasurements.producer.authorization.type }}
    acls:
      - resource:
          type: topic
          name: airqo-streams-calibrated-device-measurements-topic 
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: kcca-streams-transformed-device-measurements-topic
          patternType: literal
        operation: Read