
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2021-07-11T00:00:00Z"
  managedFields:
    - apiVersion: batch/v1beta1
      manager: kubectl
      operation: Update
      time: "2021-07-11T00:00:00Z"
  name: stage-device-registry-checks-job
  namespace: staging
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: stage-device-registry-checks-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: stage-device-registry-checks-job
              image: us.gcr.io/airqo-250220/airqo-stage-device-registry-checks-job:latest
              imagePullPolicy: Always
              env:
                - name: SLACK_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: stage-slack-webhook-url
                      key: SLACK_WEBHOOK
                - name: TENANT
                  value: airqo
                - name: DEVICE_REGISTRY_URL
                  value: http://staging-platform.airqo.net/api/v1/
                - name: TIME_INTERVAL
                  value: 3
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 00 */2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}