app:
  name: stage-airqo-train-job
  namespace: staging
  configmap: env-train-job-staging
schedule: 0 5 * * 1
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-train-job
  tag: stage-ce845393-1675841271
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 2500m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: train-job-config-files
