app:
  name: stage-airqo-train-job
  namespace: staging
  configmap: env-train-job-staging
schedule: 0 1 1 * *
suspend: true
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-train-job
  tag: stage-d80e92c9-1684396876
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 2500m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: train-job-config-files
