app:
  name: airqo-train-job
  namespace: production
  configmap: env-train-job-production
schedule: 0 1 1 * *
suspend: false
image:
  repository: eu.gcr.io/airqo-250220/airqo-train-job
  tag: prod-ffd6c4c3-1677156304
nameOverride: ""
fullnameOverride: ""
resources:
  limits:
    cpu: 8000m
    memory: 16000Mi
  requests:
    cpu: 4000m
    memory: 8000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: train-job-config-files
