apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: alpha-kafka-cluster
  namespace: alpha
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32000
          brokers:
            - broker: 0
              nodePort: 32001
              advertisedHost: 34.123.249.54
            - broker: 1
              nodePort: 32002
              advertisedHost: 34.71.105.27
            - broker: 2
              nodePort: 32003
              advertisedHost: 34.123.24.117

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        class: stage-clusters
        deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: stage-clusters
      size: 1Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
