apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: alpha-kafka-cluster
  namespace: alpha
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32000
          brokers:
            - broker: 0
              nodePort: 32001
              advertisedHost: XX.XXX.XXX.XX
            - broker: 1
              nodePort: 32002
              advertisedHost: XX.XXX.XXX.XX
            - broker: 2
              nodePort: 32003
              advertisedHost: XX.XXX.XXX.XX

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
