###########################################################
# Start deployment of schema registry - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-schema-registry
  namespace: staging
spec:
  selector:
    matchLabels:
      app: schema-registry
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: us.gcr.io/airqo-250220/stage-schema-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: schema-registry
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: stage-schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: stage-kafka-cluster-kafka-bootstrap:9092

---
kind: Service
apiVersion: v1
metadata:
  name: stage-schema-registry-svc
  namespace: staging
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081
  type: NodePort
