###########################################################
# Start deployment of schema registry - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-schema-registry
  namespace: staging
spec:
  selector:
    matchLabels:
      app: schema-registry
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: localhost:5000/stage-airqo-schema-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: schema-registry
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 192.168.49.2:32028

---
kind: Service
apiVersion: v1
metadata:
  name: schema-registry-svc
  namespace: staging
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort