app:
  name: airqo-stage-device-monitor-api
  label: device-monitor
  namespace: staging
  configmap: env-device-monitoring-staging
replicaCount: 2
image:
  repository: gcr.io/airqo-250220/airqo-stage-device-monitor-api
  tag: stage-e3bf5e25-1670597008
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 50m
    memory: 80Mi
  requests:
    cpu: 5m
    memory: 40Mi
ingress:
  enabled: false
service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 31006
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
