app:
  name: airqo-device-monitor-api
  label: device-monitor
  namespace: production
  configmap: env-device-monitoring-production
replicaCount: 3
image:
  repository: gcr.io/airqo-250220/airqo-device-monitor-api
  tag: prod-4bcf8ba0-1670941557
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 50Mi
ingress:
  enabled: false
service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 30006
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 70
