###########################################################
# Start deployment of calibrate kafka connection - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sta-calibrate-kafka
  namespace: staging
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: sta-calibrate-kafka
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sta-calibrate-kafka
    spec:
      containers:
      - name: sta-calibrate-kafka
        image: us.gcr.io/airqo-250220/airqo-stage-calibrate-kafka:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        envFrom:
          - configMapRef:
              name: stage-calibrate-config