app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-exceedance-job
  tag: prod-bfec5269-1675866864
nameOverride: ''
fullnameOverride: ''
