app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-70d63c48-1670410417
nameOverride: ''
fullnameOverride: ''
