app:
  name: kcca-exceedance-job
  namespace: staging
  configmap: env-exceedance-production
image:
  repository: gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-4b9485a3-1675498270
nameOverride: ''
fullnameOverride: ''
