app:
  name: kcca-exceedance-job
  namespace: staging
  configmap: env-exceedance-production

image:
  repository: gcr.io/airqo-250220/kcca-exceedance-job
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""
