app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-5469f6d6-1670411700
nameOverride: ''
fullnameOverride: ''
