app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-346463b8-1670404840
nameOverride: ''
fullnameOverride: ''
