app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-09ba71bd-1670928304
nameOverride: ''
fullnameOverride: ''
