app:
  name: airqo-predict-job
  namespace: production
  configmap: env-predict-job-production

schedule: 0 * * * *

image:
  repository: gcr.io/airqo-250220/airqo-predict-job
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
  # requests:
  #   cpu: 20m
  #   memory: 200Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: predict-job-config-files
