app:
  name: stage-airqo-predict-job
  namespace: staging
  configmap: env-predict-job-staging
schedule: 0 0 * * *
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-predict-job
  tag: stage-d80e92c9-1684396876
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: predict-job-config-files
