env:
  deployment_name: airqo-dev-device-registry-api
  service_name: airqo-dev-device-registry-api-svc
  labels: dev-dev-reg-api
  secret: dev-device-reg-secret
  config: dev-device-reg-secret

replicaCount: 2

image:
  repository: airqo-dev-device-registry-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8081
  targetPort: 8081
  nodePort: 31081

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: development