app:
  name: airqo-view-api
  label: view-api
  namespace: production
  configmap: stage-view-api-config
replicaCount: 2
image:
  repository: gcr.io/airqo-250220/airqo-view-api
  tag: prod-4bcf8ba0-1670941557
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
resources:
  limits:
    cpu: 2000m
    memory: 3000Mi
  requests:
    cpu: 10m
    memory: 500Mi
ingress:
  enabled: false
service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
