###########################################################
# Start deployment of AirQo raw device measurements streams application - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-airqo-raw-measurements-stream
  namespace: staging
spec:
  selector:
    matchLabels:
      app: stage-airqo-raw-measurements-stream
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stage-airqo-raw-measurements-stream
    spec:
      containers:
        - name: stage-airqo-raw-measurements-stream
          image: us.gcr.io/airqo-250220/stage-raw-device-measurements-stream:latest
          imagePullPolicy: Always
          env:
            - name: INPUT.TOPIC
              value: airqo-raw-device-measurements-topic
            - name: OUTPUT.TOPIC
              value: airqo-transformed-device-measurements-topic
            - name: TENANT
              value: airqo
            - name: APPLICATION.ID
              value: airqo-measurements-stream-3d508ddb-5b9f-493a-b96a-9a3c62dc030f
            - name: BOOTSTRAP.SERVERS
              value: stage-kafka-cluster-kafka-bootstrap:9092
            - name: SCHEMA.REGISTRY.URL
              value: http://stage-schema-registry-svc:8081
            - name: AIRQO.BASE.URL
              value: https://staging-platform.airqo.net/api/v1/
