- hosts: k8s_cluster
  become: true
  roles:
    - { role: k8s, flags: ["install_dependencies"] }

- hosts: k8s_master
  become: true
  roles:
    - { role: k8s, flags: ["configure_master"] }
    - { role: k8s, flags: ["get_join_command"] }

- hosts: k8s_workers
  become: true
  roles:
    - { role: k8s, flags: ["join_cluster"] }
