apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: dev-device-registry-db-source-connector
  namespace: dev
  labels:
    strimzi.io/cluster: dev-device-registry-db-connector-cluster
spec:
  class: com.mongodb.kafka.connect.MongoSourceConnector
  tasksMax: 1
  name: dev-device-registry-db-source-connector
  config:
    connection.uri: ${file:/opt/kafka/external-configuration/connector-config/device-registry-credentials.properties:db_uri}
    database: ${file:/opt/kafka/external-configuration/connector-config/device-registry-credentials.properties:db_name}
    collection: ${file:/opt/kafka/external-configuration/connector-config/device-registry-credentials.properties:collection_name}
    topic.prefix:
    topic.suffix:
    poll.max.batch.size: 1000
    poll.await.time.ms: 5000
    pipeline: []
    batch.size: 0
    change.stream.full.document: updateLookup
    collation: