apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: kcca-source-connector
  namespace: staging
  labels:
    strimzi.io/cluster: kcca-source-connector-cluster
spec:
  class: net.airqo.connectors.KccaSourceConnector
  tasksMax: 2
  config:
    topic: kcca-raw-device-measurements-topic
    clarityApiKey: key
    clarityApiBaseUrl: url
    pollInterval: 300000  # set to 5 minutes (5 * 60 * 1000). Note that the connector fetches for last 15 minutes
    average: raw
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false

