apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stage-vs
  namespace: staging
spec:
  hosts:
  - "*"
  gateways:
  - staging/pipeline-gateway
  http:
  - name: schema-registry
    match:
    - uri:
        prefix: /schema
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 8081
        host: stage-schema-registry-svc.staging.svc.cluster.local  
  - name: apache-airflow
    match:
    - uri:
        prefix: /airflow
    rewrite:
      uri: /airflow
    route:
    - destination:
        port:
          number: 8080
        host: airflow-svc.airflow.svc.cluster.local  
