apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airqo-calibrate-job
  namespace: production
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  schedule: "20 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: airqo-calibrate-job
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: airqo-calibrate-job
              image: us.gcr.io/airqo-250220/prod-calibrate-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: prod-calibrate-job-config
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

