app:
  name: airqo-network-uptime-api
  label: network-uptime
  namespace: production
  configmap: env-network-uptime-production

replicaCount: 3

image:
  repository: gcr.io/airqo-250220/airqo-network-uptime-api
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    # No available over the last 30 days, using estimates
    cpu: 5m
    memory: 10Mi

nodeSelector: {}
tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 8501
  protocol: TCP
  targetPort: 8501
  nodePort: 30012

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
