app:
  name: stage-update-channel-data-job
  namespace: staging
  configmap: env-update-channel-data-staging

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - compute

image:
  repository: gcr.io/airqo-250220/airqo-stage-update-channel-data-job
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    # Average usage was 0.02 vCPU and 100Mi over the last 30 days
    cpu: 20m
    memory: 200Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-update-channel-data-staging-files
