kind: Service
apiVersion: v1
metadata:
  name: postgres-airflow
  namespace: airflow
spec:
  selector:
    app: postgres-airflow
  ports:
  - name: postgres-airflow
    protocol: TCP
    port: 5432
    targetPort: 5432