kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: airflow
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-scheduler
          image: us.gcr.io/airqo-250220/airqo-apache-airflow
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["scheduler"]
          resources: {}
        - name: airflow-webserver
          image: us.gcr.io/airqo-250220/airqo-apache-airflow
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["webserver"]
          resources: {}
          readinessProbe: 
            initialDelaySeconds: 180
            timeoutSeconds: 120
            httpGet:
              path: /airflow/health
              port: 8080
      restartPolicy: Always
