kind: Service
apiVersion: v1
metadata:
 name: airflow-svc
 namespace: stage-airflow
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
  app: airflow

---
kind: Service
apiVersion: v1
metadata:
 name: airflow-svc
 namespace: airflow
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
  app: airflow