kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-airflow
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: postgres-airflow
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: postgres-airflow
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/postgresql/data/pgdata
              subPath: pgdata
          envFrom:
            - configMapRef:
                name: airflow-db-config
          resources: {}
      volumes:
        - name: dbvol
          emptyDir: {}
