kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  namespace: stage-airflow
spec:
  selector:
    matchLabels:
      app: airflow
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-scheduler
          image: us.gcr.io/airqo-250220/airqo-stage-apache-airflow
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["scheduler"]
          resources: {}
            # requests:
            #   memory: 2Mi
            #   cpu: 50m
            # limits:
            #   memory: 100Mi
            #   cpu: 100m
        - name: airflow-webserver
          image: us.gcr.io/airqo-250220/airqo-stage-apache-airflow
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["webserver"]
          resources: {}
            # requests:
            #   memory: 10Mi
            #   cpu: 100m
            # limits:
            #   memory: 500Mi
            #   cpu: 500m
          readinessProbe: 
            initialDelaySeconds: 180
            timeoutSeconds: 120
            httpGet:
              path: /stage-airflow
              port: 8080
      restartPolicy: Always
