kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  namespace: stage-airflow
spec:
  selector:
    matchLabels:
      app: airflow
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: airflow
    spec:
      # serviceAccountName: airflow
      containers:
        - name: airflow-scheduler
          image: us.gcr.io/airqo-250220/airqo-stage-apache-airflow
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["scheduler"]
          resources: {}
            # requests:
            #   memory: 2Mi
            #   cpu: 50m
            # limits:
            #   memory: 100Mi
            #   cpu: 100m
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        - name: airflow-webserver
          image: us.gcr.io/airqo-250220/airqo-stage-apache-airflow
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow"]
          args: ["webserver"]
          resources: {}
            # requests:
            #   memory: 10Mi
            #   cpu: 100m
            # limits:
            #   memory: 500Mi
            #   cpu: 500m
          readinessProbe: 
            initialDelaySeconds: 120
            timeoutSeconds: 120
            httpGet:
              path: /stage-airflow/health
              port: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: airflow-config-files
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
 name: airflow-svc
 namespace: stage-airflow
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
  app: airflow
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: airflow
 namespace: stage-airflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: airflow
 namespace: stage-airflow
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-role-binding
  namespace: stage-airflow
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: stage-airflow
roleRef:
  kind: Role
  name: airflow
  apiGroup: rbac.authorization.k8s.io
