app:
  name: airflow
  label: airflow
  namespace: pipeline
  configmap: stage-auth-api-config

replicaCount: 2
image:
  repository: gcr.io/airqo-250220/airqo-stage-auth-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    # Average usage was 0.002 vCPU and 190Mi over the last 30 days
    cpu: 10m
    memory: 180Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: stage-auth-api-config-files

ingress:
  enabled: false

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 31036

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
