apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kcca-transformed-device-measurements-topic
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # data retention set to 1 day
    segment.bytes: 1073741824