apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.app.name }}
  namespace: {{ .Values.api.app.namespace }}
  labels:
    {{- include "airqo-analytics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ .Values.api.app.label }}
  replicas: {{ .Values.api.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.api.app.label }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: {{ .Values.api.app.label }}
          image: "{{ .Values.api.images.repositories.api }}:{{ .Values.api.images.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}
              name: {{ .Values.api.app.label }}
          envFrom:
            - configMapRef:
                name: {{ .Values.api.app.configmap }}          
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        - name: celery-beat
          image: "{{ .Values.api.images.repositories.celeryBeat }}:{{ .Values.api.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.api.app.configmap }} 
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        - name: celery-worker
          image: "{{ .Values.api.images.repositories.celeryWorker }}:{{ .Values.api.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.api.app.configmap }} 
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
