namespace: production
nameOverride: ""
fullnameOverride: ""
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-analytics-api
    celeryBeat: eu.gcr.io/airqo-250220/airqo-analytics-celery-beat
    celeryWorker: eu.gcr.io/airqo-250220/airqo-analytics-celery-worker
    reportJob: eu.gcr.io/airqo-250220/airqo-analytics-report-job
  tag: prod-1b6e5014-1683239318
api:
  name: airqo-analytics-api
  label: analytics-api
  configmap: env-analytics-production
  replicaCount: 3
  podAnnotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 600Mi
    requests:
      cpu: 10m
      memory: 250Mi
job:
  name: prod-analytics-report-job
  configmap: env-analytics-report-production
  resources:
    limits:
      cpu: 1000m
      memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: prod-analytics-config-files
service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 30003
ingress:
  enabled: false
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 70
