app:
  name: stage-device-uptime-job
  namespace: staging
  configmap: env-device-uptime-staging
image:
  repository: gcr.io/airqo-250220/airqo-stage-device-uptime-job
  tag: stage-09ba71bd-1670928304
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
