apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transformed-device-measurements-topic
  namespace: alpha
  labels:
    strimzi.io/cluster: alpha-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # data retention set to 1 day
    segment.bytes: 1073741824
