app:
  name: airqo-stage-locate-api
  label: sta-locate-api
  namespace: staging
  configmap: env-locate-staging

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/airqo-stage-locate-api
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 50m
    memory: 120Mi
  requests:
    # Average usage was 0.0005 vCPU and 200Mi over the last 30 days
    cpu: 5m
    memory: 80Mi

nodeSelector: {}
tolerations: []

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 31004

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
