###########################################################
# Start deployment of AirQo raw device measurements streams application - production
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-airqo-raw-measurements-stream
  namespace: production
spec:
  selector:
    matchLabels:
      app: prod-airqo-raw-measurements-stream
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: prod-airqo-raw-measurements-stream
    spec:
      containers:
        - name: prod-airqo-raw-measurements-stream
          image: us.gcr.io/airqo-250220/prod-raw-device-measurements-stream:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: "0.2"
            limits:
              memory: 512Mi
              cpu: "1"
          envFrom:
            - configMapRef:
                name: prod-airqo-raw-measurements-stream-config
