###########################################################
# Start deployment of AirQo tahmo values streams application - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-airqo-tahmo-values-stream
  namespace: staging
spec:
  selector:
    matchLabels:
      app: stage-airqo-tahmo-values-stream
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stage-airqo-tahmo-values-stream
    spec:
      containers:
        - name: stage-airqo-tahmo-values-stream
          image: us.gcr.io/airqo-250220/stage-tahmo-values-stream:latest
          imagePullPolicy: Always
          resources: {}
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
          envFrom:
            - configMapRef:
                name: stage-tahmo-streams-config
          env:
            - name: tahmo.api.key
              valueFrom:
                secretKeyRef:
                  name: stage-tahmo-streams-secrets
                  key: tahmo.api.key
                  
            # - name: OUTPUT.TOPIC
            #   value: airqo-streams-processed-device-measurements-topic
            # - name: TENANT
            #   value: airqo
            # - name: APPLICATION.ID
            #   value: airqo-tahmo-values-stream-3d50-8ddb-5b9f-493a
            # - name: BOOTSTRAP.SERVERS
            #   value: stage-kafka-cluster-kafka-bootstrap:9092
            # - name: SCHEMA.REGISTRY.URL
            #   value: http://stage-schema-registry-svc:8081
            # - name: AIRQO.BASE.URL
            #   value: https://staging-platform.airqo.net/api/v1/
            # - name: NUM.STREAM.THREADS
            #   value: "1"
            # - name: TAHMO.BASE.URL
            #   value: https://datahub.tahmo.org/
