apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-batch-fetch-measurements
  namespace: staging
spec:
  selector:
    matchLabels:
      app: airqo-batch-fetch-measurements
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: airqo-batch-fetch-measurements
    spec:
      containers:
        - name: airqo-batch-fetch-measurements
          image: us.gcr.io/airqo-250220/airqo-batch-fetch-measurements:latest
          imagePullPolicy: Always
          env:
            - name: START_TIME
              value: "2021-01-01"
            - name: END_TIME
              value: "2021-07-30"
            - name: INTERVAL
              value: "2"
            - name: DEVICE_REGISTRY_URL
              value: "https://staging-platform.airqo.net/api/v1/"
            - name: BOOT_STRAP_SERVERS
              value: "127.0.0.1:9092"
            - name: OUTPUT_TOPIC
              value: "quickstart-events"
            - name: SCHEMA_REGISTRY_URL
              value: "http://127.0.0.1:8081"
