apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: measurements-connector-cluster
  namespace: kafka-strimzi
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.2.0
  image: ${MEASUREMENTS_CONNECTOR_CLUSTER_IMAGE}
  replicas: 2
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  externalConfiguration:
    volumes:
      - name: purple-air-connector-config
        secret:
          secretName: purple-air-credentials
  config:
    group.id: measurements-connector-cluster
    offset.storage.topic: measurements-connector-cluster-offsets
    config.storage.topic: measurements-connector-cluster-configs
    status.storage.topic: measurements-connector-cluster-status
    cleanup.policy: compact
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    config.providers: file,configmaps
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  template:
    connectContainer:
      env:
        - name: STRIMZI_IMAGE_PULL_POLICY
          value: Always
